server:
  port: 8091
  address: localhost
  compression:
    enabled: true
spring:
  application:
    name: platform-service-user
    
  profiles:
    active: dev
    include: swagger
    
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/cf_dev
    username: root
    password: 
    hikari: 
      data-source-properties: 
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
    properties: 
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
      hibernate.generate_statistics: false
      hibernate.enable_lazy_load_no_trans: true
      javax.persistence.sharedCache.mode: ALL
 
  jackson:
    serialization.indent_output: true
    
  cache:
    type: redis
    
  redis:
    host: 127.0.0.1
    database: 1
    password: foobared
  
  thymeleaf:
    cache: false
    check-template: false
      
  mobile:
    devicedelegatingviewresolver:
      enabled: true
      mobile-prefix: mobile/
      
liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.xml
  check-change-log-location: true
  
security:
  basic:
    enabled: false

logging:
  level:
    org.springframework.web: info
    
dubbo: 
  application:
    id: platform-service-user-provider
    name: user-service-provider
    version: 20180302
    owner: leoops
    organization: liuhe-cf
    environment: develop
    logger: slf4j
    qos-enable: true
    qos-port: 12345
  registry:
#    address: redis://127.0.0.1:6379
    address: zookeeper://127.0.0.1:2181
#    username: root
#    password: foobared
    subscribe: false
  protocol:
    host: 127.0.0.1
    port: 20881
    accepts: 50
    serialization: kryo
    optimizer: com.liuhecf.platform.base.api.SerializationOptimizerImpl
  scan:
    base-packages:
      com.liuhecf.platform.service.user.dubbo

aliyun: 
  access: 
    key_id: LTAIHGUm8FciwU0h
    key_secret: TkjCX6iVfxkm3FwTtMzMN795lO74Qn
  push:
    app_key: 24718934
    app_secret: 250a102f503f99854f1c6c4ffa603af6
    apns_env: DEV  #正是环境配置为PRODUCT
  sms: 
    sign: 合智汇
    templates: 
      register: SMS_128515003 #用户注册验证码：验证码${code}，您正在注册成为新用户，感谢您的支持！
      login: SMS_128515005  #登录异常验证码：验证码${code}，您正尝试异地登录，若非本人操作，请勿泄露
      password: SMS_128515002 #修改密码验证码：验证码${code}，您正在尝试修改登录密码，请妥善保管账户信息
      verify: SMS_128515006 #身份验证验证码：验证码${code}，您正在进行身份验证，打死不要告诉别人哦！
      change: SMS_128515001 #信息变更验证码：验证码${code}，您正在尝试变更重要信息，请妥善保管账户信息
    expire_in: 3 #验证码有效期（单位为分钟）
  oss:
    domain: https://liuhecf.oss-cn-shenzhen.aliyuncs.com
    endpoint: oss-cn-shenzhen.aliyuncs.com
    bucket: liuhecf

taobao: 
  openim: 
    url: http://gw.api.taobao.com/router/rest
#    url: http://gw.api.tbsandbox.com/router/rest
    app_key: 24832329
    app_secret: 7fa22264f5e5c9ed472a3f6b046442c8
    notify_id: 4028f0fb62d766630162d7ac20980000 # 系统通知IM账号
    service_id: 4028f048620952b301620955460c0000 # 系统客服IM账号

cfca:
  anxinsign:
    platId: 675AE0E071DD4FBEE05311016B0A0361
    url: https://210.74.42.33:9443/FEP/
    channel: Test
    jks:
      path: anxinsign.jks
      pwd: cfca1234
      alias: anxinsign